### ISSUE TITLE
Thumbnail is not show correct under Linux

### ISSUE THREAD

**Issue by XimingCheng** [XimingCheng/HEVCAnalyzer#2]
Thumbnail list is not show correct under Linux
Could not be one colunmn
![5](https://f.cloud.github.com/assets/2611722/591320/4093c0b8-c9ff-11e2-8033-02f35aa605fe.jpg)

**Comment by XimingCheng** [comment]
This is a bug of wxListCtrl in wxGTK! wxWidgets 2.8.12
May Change to HTML ListBox!

**Comment by lewgate** [comment]
the bug have been fixed by replacing wxListCtrl with wxSimpleHtmlListBox
