### ISSUE TITLE
wxMemoryFSHandler clean problem

### ISSUE THREAD

**Issue by XimingCheng** [XimingCheng/HEVCAnalyzer#6]
Close file before the thumbnail list finish adding images probably cause crash or assertion failure

**Comment by XimingCheng** [comment]
00:39:46 [Message] LEAVE Adding some images from 62 to 118
00:39:46 [Message] OnCloseFile() 0
00:39:46 [Message] Frame Number: 601
00:39:46 [Message] Initialize thumbnail finished
00:39:46 [Message] OnThreadEnd called
00:39:47 [Message] m_iFrameNumbers 59
00:39:47 [Message] Add some images from 0 to 4
00:39:47 [Message] LEAVE Adding some images from 0 to 4
00:39:48 [Message] Add some images from 5 to 63
00:39:49 [Message] LEAVE Adding some images from 5 to 63
00:39:49 [Message] OnCloseFile() 0
00:39:49 [Message] Frame Number: 501
00:39:49 [Message] Initialize thumbnail finished
00:39:49 [Message] m_iFrameNumbers 56
00:39:49 [Message] Add some images from 0 to 4
00:39:50 [Message] LEAVE Adding some images from 0 to 4
00:39:50 [Message] Add some images from 64 to 122
00:39:50 [Message] LEAVE Adding some images from 64 to 122
00:39:51 [Message] Add some images from 5 to 60
00:39:52 [Message] LEAVE Adding some images from 5 to 60
00:39:52 [Message] Add some images from 123 to 181
00:39:52 [Message] LEAVE Adding some images from 123 to 181
00:39:53 [Message] Add some images from 61 to 116
00:39:54 [Message] LEAVE Adding some images from 61 to 116
00:39:54 [Message] Add some images from 182 to 240
00:39:54 [Message] LEAVE Adding some images from 182 to 240
00:39:55 [Message] Add some images from 117 to 172
00:39:56 [Message] LEAVE Adding some images from 117 to 172
00:39:56 [Message] Add some images from 241 to 299
00:39:56 [Message] LEAVE Adding some images from 241 to 299
00:39:57 [Message] Add some images from 173 to 228
00:39:57 [Message] LEAVE Adding some images from 173 to 228
00:39:58 [Message] Add some images from 300 to 358
00:39:58 [Message] LEAVE Adding some images from 300 to 358
00:39:59 [Message] Add some images from 229 to 284
00:39:59 [Message] LEAVE Adding some images from 229 to 284
00:40:00 [Message] Add some images from 359 to 417
00:40:00 [Message] LEAVE Adding some images from 359 to 417
00:40:01 [Message] Add some images from 285 to 340
00:40:02 [Message] LEAVE Adding some images from 285 to 340
00:40:02 [Message] Add some images from 418 to 476
00:40:02 [Message] LEAVE Adding some images from 418 to 476
00:40:03 [Message] Add some images from 341 to 396
00:40:04 [Message] LEAVE Adding some images from 341 to 396
00:40:04 [Message] Add some images from 477 to 535
00:40:04 [Message] LEAVE Adding some images from 477 to 535
00:40:05 [Message] Add some images from 536 to 594
00:40:05 [Message] LEAVE Adding some images from 536 to 594
00:40:06 [Message] Add some images from 595 to 600
00:40:06 [Message] LEAVE Adding some images from 595 to 600
00:40:06 [Message] OnThreadEnd called
00:40:06 [Message] Add some images from 397 to 452
00:40:06 [Message] LEAVE Adding some images from 397 to 452
00:40:07 [Message] Add some images from 453 to 500
00:40:07 [Message] LEAVE Adding some images from 453 to 500
00:40:07 [Message] OnThreadEnd called

大爷的，线程居然没有成功的销毁，大爷的！看了一晚上没有找到解决办法！

**Comment by lewgate** [comment]
淡定，先搞其他的

2013/7/27 Ximing Cheng notifications@github.com

> 00:39:46 [Message] LEAVE Adding some images from 62 to 118
> 00:39:46 [Message] OnCloseFile() 0
> 00:39:46 [Message] Frame Number: 601
> 00:39:46 [Message] Initialize thumbnail finished
> 00:39:46 [Message] OnThreadEnd called
> 00:39:47 [Message] m_iFrameNumbers 59
> 00:39:47 [Message] Add some images from 0 to 4
> 00:39:47 [Message] LEAVE Adding some images from 0 to 4
> 00:39:48 [Message] Add some images from 5 to 63
> 00:39:49 [Message] LEAVE Adding some images from 5 to 63
> 00:39:49 [Message] OnCloseFile() 0
> 00:39:49 [Message] Frame Number: 501
> 00:39:49 [Message] Initialize thumbnail finished
> 00:39:49 [Message] m_iFrameNumbers 56
> 00:39:49 [Message] Add some images from 0 to 4
> 00:39:50 [Message] LEAVE Adding some images from 0 to 4
> 00:39:50 [Message] Add some images from 64 to 122
> 00:39:50 [Message] LEAVE Adding some images from 64 to 122
> 00:39:51 [Message] Add some images from 5 to 60
> 00:39:52 [Message] LEAVE Adding some images from 5 to 60
> 00:39:52 [Message] Add some images from 123 to 181
> 00:39:52 [Message] LEAVE Adding some images from 123 to 181
> 00:39:53 [Message] Add some images from 61 to 116
> 00:39:54 [Message] LEAVE Adding some images from 61 to 116
> 00:39:54 [Message] Add some images from 182 to 240
> 00:39:54 [Message] LEAVE Adding some images from 182 to 240
> 00:39:55 [Message] Add some images from 117 to 172
> 00:39:56 [Message] LEAVE Adding some images from 117 to 172
> 00:39:56 [Message] Add some images from 241 to 299
> 00:39:56 [Message] LEAVE Adding some images from 241 to 299
> 00:39:57 [Message] Add some images from 173 to 228
> 00:39:57 [Message] LEAVE Adding some images from 173 to 228
> 00:39:58 [Message] Add some images from 300 to 358
> 00:39:58 [Message] LEAVE Adding some images from 300 to 358
> 00:39:59 [Message] Add some images from 229 to 284
> 00:39:59 [Message] LEAVE Adding some images from 229 to 284
> 00:40:00 [Message] Add some images from 359 to 417
> 00:40:00 [Message] LEAVE Adding some images from 359 to 417
> 00:40:01 [Message] Add some images from 285 to 340
> 00:40:02 [Message] LEAVE Adding some images from 285 to 340
> 00:40:02 [Message] Add some images from 418 to 476
> 00:40:02 [Message] LEAVE Adding some images from 418 to 476
> 00:40:03 [Message] Add some images from 341 to 396
> 00:40:04 [Message] LEAVE Adding some images from 341 to 396
> 00:40:04 [Message] Add some images from 477 to 535
> 00:40:04 [Message] LEAVE Adding some images from 477 to 535
> 00:40:05 [Message] Add some images from 536 to 594
> 00:40:05 [Message] LEAVE Adding some images from 536 to 594
> 00:40:06 [Message] Add some images from 595 to 600
> 00:40:06 [Message] LEAVE Adding some images from 595 to 600
> 00:40:06 [Message] OnThreadEnd called
> 00:40:06 [Message] Add some images from 397 to 452
> 00:40:06 [Message] LEAVE Adding some images from 397 to 452
> 00:40:07 [Message] Add some images from 453 to 500
> 00:40:07 [Message] LEAVE Adding some images from 453 to 500
> 00:40:07 [Message] OnThreadEnd called
> 
> 大爷的，线程居然没有成功的销毁，大爷的！看了一晚上没有找到解决办法！
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/XimingCheng/HEVCAnalyzer/issues/6#issuecomment-21632849
> .

## 

Lu Qingbo
Best regard
